# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CLI Fixtures

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cli:
    name: CLI Fixtures
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run affected:lint
    - run: npm run affected:test
      env:
        CI: true
